name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Change to 'master' if your default branch is master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Debug - List all files
      - name: List all files for debugging
        run: ls -R

      # Step 3: Deploy to Firebase Hosting
      - name: Deploy to Firebase
        run: npx firebase deploy --only hosting --token "$FIREBASE_TOKEN"
