name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Change to 'master' if your default branch is master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Debug - List all files to check paths
      - name: List all files for debugging
        run: ls -R

      # Step 3: Deploy to Firebase Hosting using official GitHub Action
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
